/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.ActivityType = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class ActivityType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "AlpineSki"
     * @const
     */
    "AlpineSki": "AlpineSki",
    /**
     * value: "BackcountrySki"
     * @const
     */
    "BackcountrySki": "BackcountrySki",
    /**
     * value: "Canoeing"
     * @const
     */
    "Canoeing": "Canoeing",
    /**
     * value: "Crossfit"
     * @const
     */
    "Crossfit": "Crossfit",
    /**
     * value: "EBikeRide"
     * @const
     */
    "EBikeRide": "EBikeRide",
    /**
     * value: "Elliptical"
     * @const
     */
    "Elliptical": "Elliptical",
    /**
     * value: "Golf"
     * @const
     */
    "Golf": "Golf",
    /**
     * value: "Handcycle"
     * @const
     */
    "Handcycle": "Handcycle",
    /**
     * value: "Hike"
     * @const
     */
    "Hike": "Hike",
    /**
     * value: "IceSkate"
     * @const
     */
    "IceSkate": "IceSkate",
    /**
     * value: "InlineSkate"
     * @const
     */
    "InlineSkate": "InlineSkate",
    /**
     * value: "Kayaking"
     * @const
     */
    "Kayaking": "Kayaking",
    /**
     * value: "Kitesurf"
     * @const
     */
    "Kitesurf": "Kitesurf",
    /**
     * value: "NordicSki"
     * @const
     */
    "NordicSki": "NordicSki",
    /**
     * value: "Ride"
     * @const
     */
    "Ride": "Ride",
    /**
     * value: "RockClimbing"
     * @const
     */
    "RockClimbing": "RockClimbing",
    /**
     * value: "RollerSki"
     * @const
     */
    "RollerSki": "RollerSki",
    /**
     * value: "Rowing"
     * @const
     */
    "Rowing": "Rowing",
    /**
     * value: "Run"
     * @const
     */
    "Run": "Run",
    /**
     * value: "Sail"
     * @const
     */
    "Sail": "Sail",
    /**
     * value: "Skateboard"
     * @const
     */
    "Skateboard": "Skateboard",
    /**
     * value: "Snowboard"
     * @const
     */
    "Snowboard": "Snowboard",
    /**
     * value: "Snowshoe"
     * @const
     */
    "Snowshoe": "Snowshoe",
    /**
     * value: "Soccer"
     * @const
     */
    "Soccer": "Soccer",
    /**
     * value: "StairStepper"
     * @const
     */
    "StairStepper": "StairStepper",
    /**
     * value: "StandUpPaddling"
     * @const
     */
    "StandUpPaddling": "StandUpPaddling",
    /**
     * value: "Surfing"
     * @const
     */
    "Surfing": "Surfing",
    /**
     * value: "Swim"
     * @const
     */
    "Swim": "Swim",
    /**
     * value: "Velomobile"
     * @const
     */
    "Velomobile": "Velomobile",
    /**
     * value: "VirtualRide"
     * @const
     */
    "VirtualRide": "VirtualRide",
    /**
     * value: "VirtualRun"
     * @const
     */
    "VirtualRun": "VirtualRun",
    /**
     * value: "Walk"
     * @const
     */
    "Walk": "Walk",
    /**
     * value: "WeightTraining"
     * @const
     */
    "WeightTraining": "WeightTraining",
    /**
     * value: "Wheelchair"
     * @const
     */
    "Wheelchair": "Wheelchair",
    /**
     * value: "Windsurf"
     * @const
     */
    "Windsurf": "Windsurf",
    /**
     * value: "Workout"
     * @const
     */
    "Workout": "Workout",
    /**
     * value: "Yoga"
     * @const
     */
    "Yoga": "Yoga"  };

  /**
   * Returns a <code>ActivityType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ActivityType} The enum <code>ActivityType</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


