/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.ActivityTotal = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ActivityTotal model module.
   * @module model/ActivityTotal
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>ActivityTotal</code>.
   * A roll-up of metrics pertaining to a set of activities. Values are in seconds and meters.
   * @alias module:model/ActivityTotal
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>ActivityTotal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActivityTotal} obj Optional instance to populate.
   * @return {module:model/ActivityTotal} The populated <code>ActivityTotal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
      if (data.hasOwnProperty('distance')) {
        obj['distance'] = ApiClient.convertToType(data['distance'], 'Number');
      }
      if (data.hasOwnProperty('moving_time')) {
        obj['moving_time'] = ApiClient.convertToType(data['moving_time'], 'Number');
      }
      if (data.hasOwnProperty('elapsed_time')) {
        obj['elapsed_time'] = ApiClient.convertToType(data['elapsed_time'], 'Number');
      }
      if (data.hasOwnProperty('elevation_gain')) {
        obj['elevation_gain'] = ApiClient.convertToType(data['elevation_gain'], 'Number');
      }
      if (data.hasOwnProperty('achievement_count')) {
        obj['achievement_count'] = ApiClient.convertToType(data['achievement_count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The number of activities considered in this total.
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;
  /**
   * The total distance covered by the considered activities.
   * @member {Number} distance
   */
  exports.prototype['distance'] = undefined;
  /**
   * The total moving time of the considered activities.
   * @member {Number} moving_time
   */
  exports.prototype['moving_time'] = undefined;
  /**
   * The total elapsed time of the considered activities.
   * @member {Number} elapsed_time
   */
  exports.prototype['elapsed_time'] = undefined;
  /**
   * The total elevation gain of the considered activities.
   * @member {Number} elevation_gain
   */
  exports.prototype['elevation_gain'] = undefined;
  /**
   * The total number of achievements of the considered activities.
   * @member {Number} achievement_count
   */
  exports.prototype['achievement_count'] = undefined;



  return exports;
}));


