/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SummaryGear'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SummaryGear'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.DetailedGear = factory(root.StravaApiV3.ApiClient, root.StravaApiV3.SummaryGear);
  }
}(this, function(ApiClient, SummaryGear) {
  'use strict';




  /**
   * The DetailedGear model module.
   * @module model/DetailedGear
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>DetailedGear</code>.
   * @alias module:model/DetailedGear
   * @class
   * @implements module:model/SummaryGear
   */
  var exports = function() {
    var _this = this;

    SummaryGear.call(_this);




  };

  /**
   * Constructs a <code>DetailedGear</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetailedGear} obj Optional instance to populate.
   * @return {module:model/DetailedGear} The populated <code>DetailedGear</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      SummaryGear.constructFromObject(data, obj);
      if (data.hasOwnProperty('brand_name')) {
        obj['brand_name'] = ApiClient.convertToType(data['brand_name'], 'String');
      }
      if (data.hasOwnProperty('model_name')) {
        obj['model_name'] = ApiClient.convertToType(data['model_name'], 'String');
      }
      if (data.hasOwnProperty('frame_type')) {
        obj['frame_type'] = ApiClient.convertToType(data['frame_type'], 'Number');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
    }
    return obj;
  }

  /**
   * The gear's brand name.
   * @member {String} brand_name
   */
  exports.prototype['brand_name'] = undefined;
  /**
   * The gear's model name.
   * @member {String} model_name
   */
  exports.prototype['model_name'] = undefined;
  /**
   * The gear's frame type (bike only).
   * @member {Number} frame_type
   */
  exports.prototype['frame_type'] = undefined;
  /**
   * The gear's description.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;

  // Implement SummaryGear interface:
  /**
   * The gear's unique identifier.
   * @member {String} id
   */
exports.prototype['id'] = undefined;

  /**
   * Resource state, indicates level of detail. Possible values: 2 -> \"summary\", 3 -> \"detail\"
   * @member {Number} resource_state
   */
exports.prototype['resource_state'] = undefined;

  /**
   * Whether this gear's is the owner's default one.
   * @member {Boolean} primary
   */
exports.prototype['primary'] = undefined;

  /**
   * The gear's name.
   * @member {String} name
   */
exports.prototype['name'] = undefined;

  /**
   * The distance logged with this gear.
   * @member {Number} distance
   */
exports.prototype['distance'] = undefined;



  return exports;
}));


