/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Error'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.Fault = factory(root.StravaApiV3.ApiClient, root.StravaApiV3.Error);
  }
}(this, function(ApiClient, Error) {
  'use strict';




  /**
   * The Fault model module.
   * @module model/Fault
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Fault</code>.
   * Encapsulates the errors that may be returned from the API.
   * @alias module:model/Fault
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Fault</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fault} obj Optional instance to populate.
   * @return {module:model/Fault} The populated <code>Fault</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('errors')) {
        obj['errors'] = ApiClient.convertToType(data['errors'], [Error]);
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
    }
    return obj;
  }

  /**
   * The set of specific errors associated with this fault, if any.
   * @member {Array.<module:model/Error>} errors
   */
  exports.prototype['errors'] = undefined;
  /**
   * The message of the fault.
   * @member {String} message
   */
  exports.prototype['message'] = undefined;



  return exports;
}));


