/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BaseStream', 'model/LatLng'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BaseStream'), require('./LatLng'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.LatLngStream = factory(root.StravaApiV3.ApiClient, root.StravaApiV3.BaseStream, root.StravaApiV3.LatLng);
  }
}(this, function(ApiClient, BaseStream, LatLng) {
  'use strict';




  /**
   * The LatLngStream model module.
   * @module model/LatLngStream
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>LatLngStream</code>.
   * @alias module:model/LatLngStream
   * @class
   * @implements module:model/BaseStream
   */
  var exports = function() {
    var _this = this;

    BaseStream.call(_this);

  };

  /**
   * Constructs a <code>LatLngStream</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LatLngStream} obj Optional instance to populate.
   * @return {module:model/LatLngStream} The populated <code>LatLngStream</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      BaseStream.constructFromObject(data, obj);
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [LatLng]);
      }
    }
    return obj;
  }

  /**
   * The sequence of lat/long values for this stream
   * @member {Array.<module:model/LatLng>} data
   */
  exports.prototype['data'] = undefined;

  // Implement BaseStream interface:
  /**
   * The number of data points in this stream
   * @member {Number} original_size
   */
exports.prototype['original_size'] = undefined;

  /**
   * The level of detail (sampling) in which this stream was returned
   * @member {module:model/BaseStream.ResolutionEnum} resolution
   */
exports.prototype['resolution'] = undefined;

  /**
   * The base series used in the case the stream was downsampled
   * @member {module:model/BaseStream.SeriesTypeEnum} series_type
   */
exports.prototype['series_type'] = undefined;



  return exports;
}));


