/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.PhotosSummaryPrimary = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PhotosSummaryPrimary model module.
   * @module model/PhotosSummaryPrimary
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>PhotosSummaryPrimary</code>.
   * @alias module:model/PhotosSummaryPrimary
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>PhotosSummaryPrimary</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PhotosSummaryPrimary} obj Optional instance to populate.
   * @return {module:model/PhotosSummaryPrimary} The populated <code>PhotosSummaryPrimary</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('source')) {
        obj['source'] = ApiClient.convertToType(data['source'], 'Number');
      }
      if (data.hasOwnProperty('unique_id')) {
        obj['unique_id'] = ApiClient.convertToType(data['unique_id'], 'String');
      }
      if (data.hasOwnProperty('urls')) {
        obj['urls'] = ApiClient.convertToType(data['urls'], {'String': 'String'});
      }
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Number} source
   */
  exports.prototype['source'] = undefined;
  /**
   * @member {String} unique_id
   */
  exports.prototype['unique_id'] = undefined;
  /**
   * @member {Object.<String, String>} urls
   */
  exports.prototype['urls'] = undefined;



  return exports;
}));


