/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.Upload = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Upload model module.
   * @module model/Upload
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Upload</code>.
   * @alias module:model/Upload
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Upload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Upload} obj Optional instance to populate.
   * @return {module:model/Upload} The populated <code>Upload</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('external_id')) {
        obj['external_id'] = ApiClient.convertToType(data['external_id'], 'String');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('activity_id')) {
        obj['activity_id'] = ApiClient.convertToType(data['activity_id'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The unique identifier of the upload
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The external identifier of the upload
   * @member {String} external_id
   */
  exports.prototype['external_id'] = undefined;
  /**
   * The error associated with this upload
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * The status of this upload
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * The identifier of the activity this upload resulted into
   * @member {Number} activity_id
   */
  exports.prototype['activity_id'] = undefined;



  return exports;
}));


