/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.ZoneRange = factory(root.StravaApiV3.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ZoneRange model module.
   * @module model/ZoneRange
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>ZoneRange</code>.
   * @alias module:model/ZoneRange
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ZoneRange</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ZoneRange} obj Optional instance to populate.
   * @return {module:model/ZoneRange} The populated <code>ZoneRange</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('min')) {
        obj['min'] = ApiClient.convertToType(data['min'], 'Number');
      }
      if (data.hasOwnProperty('max')) {
        obj['max'] = ApiClient.convertToType(data['max'], 'Number');
      }
    }
    return obj;
  }

  /**
   * The minimum value in the range.
   * @member {Number} min
   */
  exports.prototype['min'] = undefined;
  /**
   * The maximum value in the range.
   * @member {Number} max
   */
  exports.prototype['max'] = undefined;



  return exports;
}));


