/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/HeartRateZoneRanges', 'model/PowerZoneRanges'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./HeartRateZoneRanges'), require('./PowerZoneRanges'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.Zones = factory(root.StravaApiV3.ApiClient, root.StravaApiV3.HeartRateZoneRanges, root.StravaApiV3.PowerZoneRanges);
  }
}(this, function(ApiClient, HeartRateZoneRanges, PowerZoneRanges) {
  'use strict';




  /**
   * The Zones model module.
   * @module model/Zones
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>Zones</code>.
   * @alias module:model/Zones
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Zones</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Zones} obj Optional instance to populate.
   * @return {module:model/Zones} The populated <code>Zones</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('heart_rate')) {
        obj['heart_rate'] = HeartRateZoneRanges.constructFromObject(data['heart_rate']);
      }
      if (data.hasOwnProperty('power')) {
        obj['power'] = PowerZoneRanges.constructFromObject(data['power']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/HeartRateZoneRanges} heart_rate
   */
  exports.prototype['heart_rate'] = undefined;
  /**
   * @member {module:model/PowerZoneRanges} power
   */
  exports.prototype['power'] = undefined;



  return exports;
}));


