/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DetailedGear', 'model/Fault'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/DetailedGear'), require('../model/Fault'));
  } else {
    // Browser globals (root is window)
    if (!root.StravaApiV3) {
      root.StravaApiV3 = {};
    }
    root.StravaApiV3.GearsApi = factory(root.StravaApiV3.ApiClient, root.StravaApiV3.DetailedGear, root.StravaApiV3.Fault);
  }
}(this, function(ApiClient, DetailedGear, Fault) {
  'use strict';

  /**
   * Gears service.
   * @module api/GearsApi
   * @version 3.0.0
   */

  /**
   * Constructs a new GearsApi. 
   * @alias module:api/GearsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getGearById operation.
     * @callback module:api/GearsApi~getGearByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/DetailedGear} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Equipment
     * Returns an equipment using its identifier.
     * @param {String} id The identifier of the gear.
     * @param {module:api/GearsApi~getGearByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/DetailedGear}
     */
    this.getGearById = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGearById");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['strava_oauth'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = DetailedGear;

      return this.apiClient.callApi(
        '/gear/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
