/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.ActivityStats();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivityStats', function() {
    it('should create an instance of ActivityStats', function() {
      // uncomment below and update the code to test ActivityStats
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be.a(StravaApiV3.ActivityStats);
    });

    it('should have the property biggestRideDistance (base name: "biggest_ride_distance")', function() {
      // uncomment below and update the code to test the property biggestRideDistance
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property biggestClimbElevationGain (base name: "biggest_climb_elevation_gain")', function() {
      // uncomment below and update the code to test the property biggestClimbElevationGain
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property recentRideTotals (base name: "recent_ride_totals")', function() {
      // uncomment below and update the code to test the property recentRideTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property recentRunTotals (base name: "recent_run_totals")', function() {
      // uncomment below and update the code to test the property recentRunTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property recentSwimTotals (base name: "recent_swim_totals")', function() {
      // uncomment below and update the code to test the property recentSwimTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property ytdRideTotals (base name: "ytd_ride_totals")', function() {
      // uncomment below and update the code to test the property ytdRideTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property ytdRunTotals (base name: "ytd_run_totals")', function() {
      // uncomment below and update the code to test the property ytdRunTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property ytdSwimTotals (base name: "ytd_swim_totals")', function() {
      // uncomment below and update the code to test the property ytdSwimTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property allRideTotals (base name: "all_ride_totals")', function() {
      // uncomment below and update the code to test the property allRideTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property allRunTotals (base name: "all_run_totals")', function() {
      // uncomment below and update the code to test the property allRunTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

    it('should have the property allSwimTotals (base name: "all_swim_totals")', function() {
      // uncomment below and update the code to test the property allSwimTotals
      //var instance = new StravaApiV3.ActivityStats();
      //expect(instance).to.be();
    });

  });

}));
