/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.ActivityZone();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivityZone', function() {
    it('should create an instance of ActivityZone', function() {
      // uncomment below and update the code to test ActivityZone
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be.a(StravaApiV3.ActivityZone);
    });

    it('should have the property score (base name: "score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property distributionBuckets (base name: "distribution_buckets")', function() {
      // uncomment below and update the code to test the property distributionBuckets
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property sensorBased (base name: "sensor_based")', function() {
      // uncomment below and update the code to test the property sensorBased
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property points (base name: "points")', function() {
      // uncomment below and update the code to test the property points
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property customZones (base name: "custom_zones")', function() {
      // uncomment below and update the code to test the property customZones
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instance = new StravaApiV3.ActivityZone();
      //expect(instance).to.be();
    });

  });

}));
