/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.DetailedSegment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetailedSegment', function() {
    it('should create an instance of DetailedSegment', function() {
      // uncomment below and update the code to test DetailedSegment
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be.a(StravaApiV3.DetailedSegment);
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property totalElevationGain (base name: "total_elevation_gain")', function() {
      // uncomment below and update the code to test the property totalElevationGain
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property map (base name: "map")', function() {
      // uncomment below and update the code to test the property map
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property effortCount (base name: "effort_count")', function() {
      // uncomment below and update the code to test the property effortCount
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property athleteCount (base name: "athlete_count")', function() {
      // uncomment below and update the code to test the property athleteCount
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property hazardous (base name: "hazardous")', function() {
      // uncomment below and update the code to test the property hazardous
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

    it('should have the property starCount (base name: "star_count")', function() {
      // uncomment below and update the code to test the property starCount
      //var instance = new StravaApiV3.DetailedSegment();
      //expect(instance).to.be();
    });

  });

}));
