/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.DetailedAthlete();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DetailedAthlete', function() {
    it('should create an instance of DetailedAthlete', function() {
      // uncomment below and update the code to test DetailedAthlete
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be.a(StravaApiV3.DetailedAthlete);
    });

    it('should have the property followerCount (base name: "follower_count")', function() {
      // uncomment below and update the code to test the property followerCount
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property friendCount (base name: "friend_count")', function() {
      // uncomment below and update the code to test the property friendCount
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property mutualFriendCount (base name: "mutual_friend_count")', function() {
      // uncomment below and update the code to test the property mutualFriendCount
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property measurementPreference (base name: "measurement_preference")', function() {
      // uncomment below and update the code to test the property measurementPreference
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property ftp (base name: "ftp")', function() {
      // uncomment below and update the code to test the property ftp
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property clubs (base name: "clubs")', function() {
      // uncomment below and update the code to test the property clubs
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property bikes (base name: "bikes")', function() {
      // uncomment below and update the code to test the property bikes
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

    it('should have the property shoes (base name: "shoes")', function() {
      // uncomment below and update the code to test the property shoes
      //var instance = new StravaApiV3.DetailedAthlete();
      //expect(instance).to.be();
    });

  });

}));
