/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.Route();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Route', function() {
    it('should create an instance of Route', function() {
      // uncomment below and update the code to test Route
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be.a(StravaApiV3.Route);
    });

    it('should have the property athlete (base name: "athlete")', function() {
      // uncomment below and update the code to test the property athlete
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property elevationGain (base name: "elevation_gain")', function() {
      // uncomment below and update the code to test the property elevationGain
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property map (base name: "map")', function() {
      // uncomment below and update the code to test the property map
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property _private (base name: "private")', function() {
      // uncomment below and update the code to test the property _private
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property starred (base name: "starred")', function() {
      // uncomment below and update the code to test the property starred
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property subType (base name: "sub_type")', function() {
      // uncomment below and update the code to test the property subType
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property segments (base name: "segments")', function() {
      // uncomment below and update the code to test the property segments
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

    it('should have the property directions (base name: "directions")', function() {
      // uncomment below and update the code to test the property directions
      //var instance = new StravaApiV3.Route();
      //expect(instance).to.be();
    });

  });

}));
