/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.Split();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Split', function() {
    it('should create an instance of Split', function() {
      // uncomment below and update the code to test Split
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be.a(StravaApiV3.Split);
    });

    it('should have the property averageSpeed (base name: "average_speed")', function() {
      // uncomment below and update the code to test the property averageSpeed
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property elapsedTime (base name: "elapsed_time")', function() {
      // uncomment below and update the code to test the property elapsedTime
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property elevationDifference (base name: "elevation_difference")', function() {
      // uncomment below and update the code to test the property elevationDifference
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property paceZone (base name: "pace_zone")', function() {
      // uncomment below and update the code to test the property paceZone
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property movingTime (base name: "moving_time")', function() {
      // uncomment below and update the code to test the property movingTime
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

    it('should have the property split (base name: "split")', function() {
      // uncomment below and update the code to test the property split
      //var instance = new StravaApiV3.Split();
      //expect(instance).to.be();
    });

  });

}));
