/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.SummarySegmentEffort();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SummarySegmentEffort', function() {
    it('should create an instance of SummarySegmentEffort', function() {
      // uncomment below and update the code to test SummarySegmentEffort
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be.a(StravaApiV3.SummarySegmentEffort);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

    it('should have the property elapsedTime (base name: "elapsed_time")', function() {
      // uncomment below and update the code to test the property elapsedTime
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

    it('should have the property startDateLocal (base name: "start_date_local")', function() {
      // uncomment below and update the code to test the property startDateLocal
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

    it('should have the property distance (base name: "distance")', function() {
      // uncomment below and update the code to test the property distance
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

    it('should have the property isKom (base name: "is_kom")', function() {
      // uncomment below and update the code to test the property isKom
      //var instance = new StravaApiV3.SummarySegmentEffort();
      //expect(instance).to.be();
    });

  });

}));
