/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.UpdatableActivity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UpdatableActivity', function() {
    it('should create an instance of UpdatableActivity', function() {
      // uncomment below and update the code to test UpdatableActivity
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be.a(StravaApiV3.UpdatableActivity);
    });

    it('should have the property commute (base name: "commute")', function() {
      // uncomment below and update the code to test the property commute
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

    it('should have the property trainer (base name: "trainer")', function() {
      // uncomment below and update the code to test the property trainer
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

    it('should have the property gearId (base name: "gear_id")', function() {
      // uncomment below and update the code to test the property gearId
      //var instance = new StravaApiV3.UpdatableActivity();
      //expect(instance).to.be();
    });

  });

}));
