/**
 * Strava API v3
 * Strava API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StravaApiV3);
  }
}(this, function(expect, StravaApiV3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StravaApiV3.ActivitiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ActivitiesApi', function() {
    describe('createActivity', function() {
      it('should call createActivity successfully', function(done) {
        //uncomment below and update the code to test createActivity
        //instance.createActivity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getActivityById', function() {
      it('should call getActivityById successfully', function(done) {
        //uncomment below and update the code to test getActivityById
        //instance.getActivityById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCommentsByActivityId', function() {
      it('should call getCommentsByActivityId successfully', function(done) {
        //uncomment below and update the code to test getCommentsByActivityId
        //instance.getCommentsByActivityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKudoersByActivityId', function() {
      it('should call getKudoersByActivityId successfully', function(done) {
        //uncomment below and update the code to test getKudoersByActivityId
        //instance.getKudoersByActivityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLapsByActivityId', function() {
      it('should call getLapsByActivityId successfully', function(done) {
        //uncomment below and update the code to test getLapsByActivityId
        //instance.getLapsByActivityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLoggedInAthleteActivities', function() {
      it('should call getLoggedInAthleteActivities successfully', function(done) {
        //uncomment below and update the code to test getLoggedInAthleteActivities
        //instance.getLoggedInAthleteActivities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getZonesByActivityId', function() {
      it('should call getZonesByActivityId successfully', function(done) {
        //uncomment below and update the code to test getZonesByActivityId
        //instance.getZonesByActivityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateActivityById', function() {
      it('should call updateActivityById successfully', function(done) {
        //uncomment below and update the code to test updateActivityById
        //instance.updateActivityById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
